# fly.toml app configuration file generated for next-express-todo-backend-v3-fix on 2024-04-06T13:59:54-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'next-express-todo-backend-v3-fix'
primary_region = 'scl'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
